version: "3.8"
services:
  dev-db:
    container_name: 'dev-db'
    restart: always
    image: postgres:${POSTGRES_VERSION}
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - 'development'
  test-db:
    container_name: 'test-db'
    image: postgres:${POSTGRES_VERSION}
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - 'development'
networks:
  development:
    name: test-nest_development
